services:

  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    env_file:
      - db_creds.env
    volumes:
      - 'db_volume:/var/lib/postgresql/data/'

  project:
    build: ./project/
    env_file:
      - db_creds.env
    depends_on:
      - db
    command: /bin/sh -c "python script.py ${mode} ${sequence} ; tail -f /dev/null"
#      python script.py ${mode} ${sequence}
#      tail -f /dev/null
volumes:
  db_volume: